# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel


class HealthResponse(UniversalBaseModel):
    """
    Examples
    --------
    from proofstate.health import HealthResponse

    HealthResponse(
        version="1.25.0",
        status="OK",
    )
    """

    version: str = pydantic.Field()
    """
    ProofState server version
    """

    status: str

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
        extra="allow", frozen=True
    )
