# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import (
    AsyncRawBlobStorageIntegrationsClient,
    RawBlobStorageIntegrationsClient,
)
from .types.blob_storage_export_field_group import BlobStorageExportFieldGroup
from .types.blob_storage_export_frequency import BlobStorageExportFrequency
from .types.blob_storage_export_mode import BlobStorageExportMode
from .types.blob_storage_export_source import BlobStorageExportSource
from .types.blob_storage_integration_deletion_response import (
    BlobStorageIntegrationDeletionResponse,
)
from .types.blob_storage_integration_file_type import BlobStorageIntegrationFileType
from .types.blob_storage_integration_response import BlobStorageIntegrationResponse
from .types.blob_storage_integration_status_response import (
    BlobStorageIntegrationStatusResponse,
)
from .types.blob_storage_integration_type import BlobStorageIntegrationType
from .types.blob_storage_integrations_response import BlobStorageIntegrationsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BlobStorageIntegrationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBlobStorageIntegrationsClient(
            client_wrapper=client_wrapper
        )

    @property
    def with_raw_response(self) -> RawBlobStorageIntegrationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBlobStorageIntegrationsClient
        """
        return self._raw_client

    def get_blob_storage_integrations(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationsResponse:
        """
        Get all blob storage integrations for the organization (requires organization-scoped API key)

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationsResponse

        Examples
        --------
        from proofstate import ProofStateAPI

        client = ProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )
        client.blob_storage_integrations.get_blob_storage_integrations()
        """
        _response = self._raw_client.get_blob_storage_integrations(
            request_options=request_options
        )
        return _response.data

    def upsert_blob_storage_integration(
        self,
        *,
        project_id: str,
        type: BlobStorageIntegrationType,
        bucket_name: str,
        region: str,
        export_frequency: BlobStorageExportFrequency,
        enabled: bool,
        force_path_style: bool,
        file_type: BlobStorageIntegrationFileType,
        export_mode: BlobStorageExportMode,
        endpoint: typing.Optional[str] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        prefix: typing.Optional[str] = OMIT,
        export_start_date: typing.Optional[dt.datetime] = OMIT,
        compressed: typing.Optional[bool] = OMIT,
        export_source: typing.Optional[BlobStorageExportSource] = OMIT,
        export_field_groups: typing.Optional[
            typing.Sequence[BlobStorageExportFieldGroup]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BlobStorageIntegrationResponse:
        """
        Create or update a blob storage integration for a specific project (requires organization-scoped API key). The configuration is validated by performing a test upload to the bucket.

        Parameters
        ----------
        project_id : str
            ID of the project in which to configure the blob storage integration

        type : BlobStorageIntegrationType

        bucket_name : str
            Name of the storage bucket. For AZURE_BLOB_STORAGE, must be a valid Azure container name (3-63 chars, lowercase letters, numbers, and hyphens only, must start and end with a letter or number, no consecutive hyphens).

        region : str
            Storage region used by S3-compatible clients (AWS, GCS, Cloudflare R2, MinIO, Azure location IDs such as eastus, OCI). Leading and trailing whitespace is removed. The remaining value must be 1-63 letters, numbers, or hyphens, and cannot start or end with a hyphen. Examples: us-east-1, europe-west1, eastus, auto.

        export_frequency : BlobStorageExportFrequency

        enabled : bool
            Whether the integration is active

        force_path_style : bool
            Use path-style URLs for S3 requests

        file_type : BlobStorageIntegrationFileType

        export_mode : BlobStorageExportMode

        endpoint : typing.Optional[str]
            Custom endpoint URL (required for S3_COMPATIBLE type)

        access_key_id : typing.Optional[str]
            Access key ID for authentication

        secret_access_key : typing.Optional[str]
            Secret access key for authentication (will be encrypted when stored)

        prefix : typing.Optional[str]
            Path prefix for exported files (must end with forward slash if provided)

        export_start_date : typing.Optional[dt.datetime]
            Custom start date for exports (required when exportMode is FROM_CUSTOM_DATE). Must not be in the future (27 h tolerance for timezone differences).

        compressed : typing.Optional[bool]
            Enable gzip compression for exported files (.csv.gz, .json.gz, .jsonl.gz). Defaults to true.

        export_source : typing.Optional[BlobStorageExportSource]
            Data to export. When omitted on update, the existing value is preserved. When omitted on create, the server selects a source supported by the deployment. Required when `exportFieldGroups` is provided.



        export_field_groups : typing.Optional[typing.Sequence[BlobStorageExportFieldGroup]]
            Field groups to include in each exported observation row. Applies to all export sources; must include `core` if provided. When omitted on create, the column default (all groups) applies. When omitted on update, the existing value is preserved.

            `exportFieldGroups` requires `exportSource` to be provided in the same request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationResponse

        Examples
        --------
        from proofstate import ProofStateAPI
        from proofstate.blob_storage_integrations import (
            BlobStorageExportFrequency,
            BlobStorageExportMode,
            BlobStorageIntegrationFileType,
            BlobStorageIntegrationType,
        )

        client = ProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )
        client.blob_storage_integrations.upsert_blob_storage_integration(
            project_id="projectId",
            type=BlobStorageIntegrationType.S3,
            bucket_name="bucketName",
            region="region",
            export_frequency=BlobStorageExportFrequency.EVERY20MINUTES,
            enabled=True,
            force_path_style=True,
            file_type=BlobStorageIntegrationFileType.JSON,
            export_mode=BlobStorageExportMode.FULL_HISTORY,
        )
        """
        _response = self._raw_client.upsert_blob_storage_integration(
            project_id=project_id,
            type=type,
            bucket_name=bucket_name,
            region=region,
            export_frequency=export_frequency,
            enabled=enabled,
            force_path_style=force_path_style,
            file_type=file_type,
            export_mode=export_mode,
            endpoint=endpoint,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            prefix=prefix,
            export_start_date=export_start_date,
            compressed=compressed,
            export_source=export_source,
            export_field_groups=export_field_groups,
            request_options=request_options,
        )
        return _response.data

    def get_blob_storage_integration_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationStatusResponse:
        """
        Get the sync status of a blob storage integration by integration ID (requires organization-scoped API key)

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationStatusResponse

        Examples
        --------
        from proofstate import ProofStateAPI

        client = ProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )
        client.blob_storage_integrations.get_blob_storage_integration_status(
            id="id",
        )
        """
        _response = self._raw_client.get_blob_storage_integration_status(
            id, request_options=request_options
        )
        return _response.data

    def delete_blob_storage_integration(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationDeletionResponse:
        """
        Delete a blob storage integration by ID (requires organization-scoped API key)

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationDeletionResponse

        Examples
        --------
        from proofstate import ProofStateAPI

        client = ProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )
        client.blob_storage_integrations.delete_blob_storage_integration(
            id="id",
        )
        """
        _response = self._raw_client.delete_blob_storage_integration(
            id, request_options=request_options
        )
        return _response.data


class AsyncBlobStorageIntegrationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBlobStorageIntegrationsClient(
            client_wrapper=client_wrapper
        )

    @property
    def with_raw_response(self) -> AsyncRawBlobStorageIntegrationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBlobStorageIntegrationsClient
        """
        return self._raw_client

    async def get_blob_storage_integrations(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationsResponse:
        """
        Get all blob storage integrations for the organization (requires organization-scoped API key)

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationsResponse

        Examples
        --------
        import asyncio

        from proofstate import AsyncProofStateAPI

        client = AsyncProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.blob_storage_integrations.get_blob_storage_integrations()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_blob_storage_integrations(
            request_options=request_options
        )
        return _response.data

    async def upsert_blob_storage_integration(
        self,
        *,
        project_id: str,
        type: BlobStorageIntegrationType,
        bucket_name: str,
        region: str,
        export_frequency: BlobStorageExportFrequency,
        enabled: bool,
        force_path_style: bool,
        file_type: BlobStorageIntegrationFileType,
        export_mode: BlobStorageExportMode,
        endpoint: typing.Optional[str] = OMIT,
        access_key_id: typing.Optional[str] = OMIT,
        secret_access_key: typing.Optional[str] = OMIT,
        prefix: typing.Optional[str] = OMIT,
        export_start_date: typing.Optional[dt.datetime] = OMIT,
        compressed: typing.Optional[bool] = OMIT,
        export_source: typing.Optional[BlobStorageExportSource] = OMIT,
        export_field_groups: typing.Optional[
            typing.Sequence[BlobStorageExportFieldGroup]
        ] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BlobStorageIntegrationResponse:
        """
        Create or update a blob storage integration for a specific project (requires organization-scoped API key). The configuration is validated by performing a test upload to the bucket.

        Parameters
        ----------
        project_id : str
            ID of the project in which to configure the blob storage integration

        type : BlobStorageIntegrationType

        bucket_name : str
            Name of the storage bucket. For AZURE_BLOB_STORAGE, must be a valid Azure container name (3-63 chars, lowercase letters, numbers, and hyphens only, must start and end with a letter or number, no consecutive hyphens).

        region : str
            Storage region used by S3-compatible clients (AWS, GCS, Cloudflare R2, MinIO, Azure location IDs such as eastus, OCI). Leading and trailing whitespace is removed. The remaining value must be 1-63 letters, numbers, or hyphens, and cannot start or end with a hyphen. Examples: us-east-1, europe-west1, eastus, auto.

        export_frequency : BlobStorageExportFrequency

        enabled : bool
            Whether the integration is active

        force_path_style : bool
            Use path-style URLs for S3 requests

        file_type : BlobStorageIntegrationFileType

        export_mode : BlobStorageExportMode

        endpoint : typing.Optional[str]
            Custom endpoint URL (required for S3_COMPATIBLE type)

        access_key_id : typing.Optional[str]
            Access key ID for authentication

        secret_access_key : typing.Optional[str]
            Secret access key for authentication (will be encrypted when stored)

        prefix : typing.Optional[str]
            Path prefix for exported files (must end with forward slash if provided)

        export_start_date : typing.Optional[dt.datetime]
            Custom start date for exports (required when exportMode is FROM_CUSTOM_DATE). Must not be in the future (27 h tolerance for timezone differences).

        compressed : typing.Optional[bool]
            Enable gzip compression for exported files (.csv.gz, .json.gz, .jsonl.gz). Defaults to true.

        export_source : typing.Optional[BlobStorageExportSource]
            Data to export. When omitted on update, the existing value is preserved. When omitted on create, the server selects a source supported by the deployment. Required when `exportFieldGroups` is provided.



        export_field_groups : typing.Optional[typing.Sequence[BlobStorageExportFieldGroup]]
            Field groups to include in each exported observation row. Applies to all export sources; must include `core` if provided. When omitted on create, the column default (all groups) applies. When omitted on update, the existing value is preserved.

            `exportFieldGroups` requires `exportSource` to be provided in the same request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationResponse

        Examples
        --------
        import asyncio

        from proofstate import AsyncProofStateAPI
        from proofstate.blob_storage_integrations import (
            BlobStorageExportFrequency,
            BlobStorageExportMode,
            BlobStorageIntegrationFileType,
            BlobStorageIntegrationType,
        )

        client = AsyncProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.blob_storage_integrations.upsert_blob_storage_integration(
                project_id="projectId",
                type=BlobStorageIntegrationType.S3,
                bucket_name="bucketName",
                region="region",
                export_frequency=BlobStorageExportFrequency.EVERY20MINUTES,
                enabled=True,
                force_path_style=True,
                file_type=BlobStorageIntegrationFileType.JSON,
                export_mode=BlobStorageExportMode.FULL_HISTORY,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upsert_blob_storage_integration(
            project_id=project_id,
            type=type,
            bucket_name=bucket_name,
            region=region,
            export_frequency=export_frequency,
            enabled=enabled,
            force_path_style=force_path_style,
            file_type=file_type,
            export_mode=export_mode,
            endpoint=endpoint,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            prefix=prefix,
            export_start_date=export_start_date,
            compressed=compressed,
            export_source=export_source,
            export_field_groups=export_field_groups,
            request_options=request_options,
        )
        return _response.data

    async def get_blob_storage_integration_status(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationStatusResponse:
        """
        Get the sync status of a blob storage integration by integration ID (requires organization-scoped API key)

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationStatusResponse

        Examples
        --------
        import asyncio

        from proofstate import AsyncProofStateAPI

        client = AsyncProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.blob_storage_integrations.get_blob_storage_integration_status(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_blob_storage_integration_status(
            id, request_options=request_options
        )
        return _response.data

    async def delete_blob_storage_integration(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BlobStorageIntegrationDeletionResponse:
        """
        Delete a blob storage integration by ID (requires organization-scoped API key)

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BlobStorageIntegrationDeletionResponse

        Examples
        --------
        import asyncio

        from proofstate import AsyncProofStateAPI

        client = AsyncProofStateAPI(
            x_proofstate_sdk_name="YOUR_X_PROOFSTATE_SDK_NAME",
            x_proofstate_sdk_version="YOUR_X_PROOFSTATE_SDK_VERSION",
            x_proofstate_public_key="YOUR_PROOFSTATE_PUBLIC_KEY",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.blob_storage_integrations.delete_blob_storage_integration(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_blob_storage_integration(
            id, request_options=request_options
        )
        return _response.data
